### ISSUE TITLE
cellular_sock.c: wondering if the following code is correct (need a comma?)

### ISSUE THREAD

**Issue by wes3** [u-blox/cellular#5]
I could be wrong here, but does the following code need a comma before the 1? I am very new to this code so I could be missing something. Syntax for AT command should be: AT+USOCTL=0,1 (assuming, of course, socket id 0). And sorry for the poor copy and paste but I think you get the idea.

In function cellularSockClose():
    if ((pContainer->socket.protocol == CELLULAR_SOCK_PROTOCOL_TCP) &&
         (pContainer->socket.state == CELLULAR_SOCK_STATE_CONNECTED)) {
                cellular_ctrl_at_write_int(1);
                finalState = CELLULAR_SOCK_STATE_CLOSING;
    }

**Comment by ubxlib** [comment]
Hi there: no, it's OK, the underlying `cellular_ctrl_at_xx()` functions deal with delimeters automagically, adding them as necessary (none for the first parameter written, one before the next parameter is written, etc).

Nice MyNewt porting by the way!

Purely FYI, we're now in the process of creating a new repo, named "ubxlib", which basically does what this one does but will be extended/renamed so that all u-blox modules (wifi, BT, GNSS) can be driven through it.  Hence you'll see less activity here and, hopefully around the end of July, a new thing will appear.

**Comment by wes3** [comment]
Well, it is not a nice port yet :-). Ah, I see it now. It is in check_cmd_send(). Thanks!
